### ISSUE TITLE
Using make command inside other make command

### ISSUE THREAD

**Issue by saileshbro** [yankeexe/makefile-tutorial-sample-repo#1]
Hey, thanks for the video. I just wanted to know a thing. Let's say if we create a command called `check-format` and reuse the old `check` and `format` command. Is this the valid syntax to use both the commands?
```yaml
check-format: # check and format
	@${MAKE} check && ${MAKE} format
```

**Comment by yankeexe** [comment]
@saileshbro if you are trying to reference a target that is already created,  you can simply just reference the target as a dependency. Here's an example: 

> Please note that we are not including any `recipe` here.

```bash 
check-format: check format
```

You might only want to use the recursive `${MAKE}` command if you are trying to run **targets** that are in *sub-directories*. Even so, there's already an [`include`](https://yankee.dev/streamline-projects-using-makefile#include-other-makefiles) command to do It, so you may never have to use it.

---

The only reason I am using recursive make here is to invoke the `jobs` flag which is available in **make** CLI.
https://github.com/yankeexe/makefile-tutorial-sample-repo/blob/9d2d4fa33f1c49e905984972327217e52c7440dd/Makefile#L42
Hope this helps ✅

**Comment by saileshbro** [comment]
@yankeexe great thanks.
